### ISSUE TITLE
Hypriot/ARM images

### ISSUE THREAD

**Issue by oberstet** [docker-library/pypy#11]
It would be awesome to have PyPy images for Docker on ARM: Hypriot http://blog.hypriot.com/

**Comment by yosifkit** [comment]
ARMv5, ARMv7 or ARMv8?  We have some "temporary, experimental builds" as described in the [official-images readme](https://github.com/docker-library/official-images/tree/0ea55f2082ad769af7ccdc9f4a1dab622af91ee7#architectures-other-than-amd64).

**Comment by oberstet** [comment]
For Pi2/3, which means ([as far as I understand](https://github.com/raspberrypi/linux/issues/1310)), a `armhf` ARMv7 kernel/userland on both Pi2 and Pi3 (though the latter is technically a ARMv8).

**Comment by oberstet** [comment]
I was [told](https://github.com/crossbario/crossbar-docker/issues/4#issuecomment-210759970) that `FROM resin/rpi-raspbian:jessie` would be a good start for the [software](https://github.com/crossbario/crossbar) I'd like to create images for.

**Comment by tianon** [comment]
For the RPi2/3, any of the images in the Hub's "armhf" namespace (which
includes pypy) should be functional.

**Comment by oberstet** [comment]
@tianon I suppose this https://hub.docker.com/r/armhf/pypy/ ? awesome, thanks!

**Comment by tianon** [comment]
This is _officially_ "fixed" by https://github.com/docker-library/pypy/pull/16 / https://github.com/docker-library/official-images/pull/3364. :+1:

**Comment by tianon** [comment]
(and will show up under `arm32v7/pypy` when it's finished)

**Comment by oberstet** [comment]
@tianon awesome! so the official base images are the following, right? I am still catching up with the new multi arch stuff ..

**PyPy:**

* https://hub.docker.com/r/i386/pypy/
* https://hub.docker.com/r/amd64/pypy/
* https://hub.docker.com/r/arm32v7/pypy/
* https://hub.docker.com/r/arm64v8/pypy/ (**not avail as not supported upstream yet!**)

**CPython:**

* https://hub.docker.com/r/i386/python/
* https://hub.docker.com/r/amd64/python/
* https://hub.docker.com/r/arm32v7/python/
* https://hub.docker.com/r/arm64v8/python/

**Comment by tianon** [comment]
Yes, that is correct :+1:
