### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [docker-library/pypy#17]
I want to build this image on arm64 but I don't find some file to support arm64 on https://bitbucket.org/pypy/pypy/downloads/ , So I want to know this image whether or not to support arm64

**Comment by tianon** [comment]
See https://bitbucket.org/pypy/pypy/issues/2331/armv8-aarch64-or-aarch32-support, especially https://bitbucket.org/pypy/pypy/issues/2331/armv8-aarch64-or-aarch32-support#comment-37490175:

> The core PyPy team has got no plan to support aarch64 at the moment. I can't speak for others, but as far as I'm concerned I have no time available to work on it even if I got money and access to a machine.

If upstream's stance changes and they start releasing binaries for arm64, we can reconsider consuming them. :+1:

**Comment by longquan7** [comment]
@tianon OK,thanks

**Comment by mmarmm** [comment]
@tianon Hi, it appears upstream stance has now changed, could we introduce a development version to start testing when available or is it too early? Could we open this back up in the meantime while we're waiting? Thanks.

https://morepypy.blogspot.com/2018/11/hello-everyone-at-pypy-we-are-trying-to.html

**Comment by tianon** [comment]
Sure, sounds reasonable.

**Comment by tianon** [comment]
7.1.0 is now released (quite a few months later) and still no arm64 support upstream :disappointed: (likely stuck on some language implementation issues; unfortunately nothing we can really control or help with :disappointed:)

(I'm going to close this for now.  When upstream starts publishing arm64 binaries again, we'll happily consume them as much as we can! :+1:)

**Comment by fijal** [comment]
Hey. Arm64 support landed officially in PyPy as of a few minutes ago. We don't have a release yet, but what can we do for this to be officially included?

**Comment by tianon** [comment]
Unfortunately, we consume from the official releases (https://bitbucket.org/pypy/pypy/downloads/), so I think this will need to wait for a release. :disappointed:

**Comment by fijal** [comment]
Would you be interested in a pre-release? I can add a thing to pypy/downloads if you need

**Comment by tianon** [comment]
Absolutely! I'm a big fan of incorporating pre-releases (often to the chagrin of @yosifkit :innocent: ).

**Comment by fijal** [comment]
Hey.

I've uploaded pypy2.7 prerelease for arm64 to https://bitbucket.org/pypy/pypy/downloads/pypy-v7.2-pre-aarch64.tar.bz2

Let me know if it works for you!

**Comment by tianon** [comment]
That's definitely neat, and I think it's useful to create a Docker image from!  What I'm not sure about is where it would fit within this image though -- we're currently packaging each release branch across the set of supported architectures we have in overlap with what's released, so I'm not sure what we would label this build especially since it's arm64-only and doesn't correspond to anything else. :confused: 

Any ideas/thoughts?  Maybe this makes more sense as a community image on Docker Hub for now to get folks to try it out?  (any idea who holds the keys to the https://hub.docker.com/u/pypy organization? :smile:)

**Comment by fijal** [comment]
I think the answer is "we just wait for the release", which should happen in the next few weeks.

**Comment by lag-linaro** [comment]
https://bitbucket.org/pypy/pypy/downloads/

Tadaaaaaa!

**Comment by lag-linaro** [comment]
AArch64 pre-release has been out for a couple of months now.

@tianon could you please re-open this ticket.

@fijal any update on a proper release yet?

**Comment by fijal** [comment]
Hey

PyPy release is upcoming and aarch64 is a part of it. You can look up latest builds from various branches (trunk, py3.6, upcoming release when it comes along) here: http://buildbot.pypy.org/nightly/

**Comment by tianon** [comment]
Unfortunately, we're having to remove this support again in #69 thanks to linking changes (`libffi.so.6` and `libtinfow.so.6`). :disappointed:
