### ISSUE TITLE
`python` executable is cpython 2.7

### ISSUE THREAD

**Issue by beniwohli** [docker-library/pypy#21]
In the Dockerfile, the intention seems to be to override the system python

https://github.com/docker-library/pypy/blob/90d6f08b46c99c7cccae534f4ba003c132cc1afe/Dockerfile.template#L3-L4

This isn't the case though:

    $ docker run --rm pypy:3 python --version
    Python 2.7.9

I "fixed" it in my inheriting Dockerfile with 

    RUN if command -v pypy3; then ln -s $(command -v pypy3) /usr/local/bin/python; fi

but that seems suboptimal.

**Comment by tianon** [comment]
We don't symlink from PyPy to Python at all -- the fix here is that we need to update the comment to say "distribution pypy" instead.
