### ISSUE TITLE
Obsolete Debian release is being used

### ISSUE THREAD

**Issue by mlowicki** [docker-library/pypy#24]
Jessie is marked as obsolete - https://www.debian.org/releases/.

**Comment by yosifkit** [comment]
There will be a final release later this month and it will then transition to https://wiki.debian.org/LTS; so it is only obsolete in the eyes of the Debian release and security teams.

We would want to update the image like https://github.com/docker-library/python/pull/215, to have explicit aliases for jessie and stretch so that users would be able to stick to one while they evaluate the move to a new base distribution.

**Comment by mlowicki** [comment]
Yes, that would be perfect an generally the way docker-library/python works, makes our life much easier when it goes to handling upgrades or security issues.

**Comment by tianon** [comment]
https://github.com/docker-library/pypy/pull/27 is the first step; once we get those published I'll be doing a bump to `stretch`. :+1:

**Comment by KOLANICH** [comment]
It is still not fixed.

**Comment by tianon** [comment]
We will not be consuming binaries directly from unstable, nor will we be consuming packages built and part of Debian unless upstream specifically tells us that is what they would prefer.

At the moment, PyPy upstream recommends that we use their officially published binaries, so that is what we are doing, and those binaries have constraints that we can't trivially work around within Debian Stretch and Debian Jessie is still supported within the Debian project (it's just that it's now supported by the LTS team instead of the security and release teams, so to a lesser extent).

Ideally, we'd switch to using the "Portable Linux Binaries" PyPy recommends on their download page (https://github.com/squeaky-pl/portable-pypy#portable-pypy-distribution-for-linux), but those are unfortunately _very_ limited in multi-architecture support, which would be a shame to lose here (and is considered an avenue of absolute last resort only if we absolutely must, as in Debian Jessie is no longer officially supported).

If you wish to use a newer Debian base and are OK with Debian's `pypy` package, it is _trivial_ for you to do so without our support:

```dockerfile
FROM debian:stretch
RUN apt-get update && apt-get install -y pypy
```

**Comment by tianon** [comment]
Have you tried automated builds? They definitely take most of the pain out
of maintaining (add repository links and they automatically rebuild on base
image updates too).

**Comment by KOLANICH** [comment]
>Have you tried automated builds? They definitely take most of the pain out of maintaining (add repository links and they automatically rebuild on base image updates too).

No, I have not heard about this feature. Thank you.

**Comment by soerenmartius** [comment]
seems like we need to update to stretch now. Building the image already fails since the mirrors don't exist anymore.

https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

**Comment by soerenmartius** [comment]
`Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [822 kB]
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:3 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://deb.debian.org jessie-updates Release.gpg
Get:4 http://deb.debian.org jessie Release [148 kB]
Ign http://deb.debian.org jessie-updates Release
Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
`

**Comment by tianon** [comment]
Yep, see https://github.com/debuerreotype/docker-debian-artifacts/issues/66#issuecomment-476648047.  We still have a _little_ runway with the Debian LTS project, but not very much.

**Comment by soerenmartius** [comment]
it's a reasonable idea to upgrade the distribution asap. I've been wrapping my head around upgrading to stretch today but end up having some weird issue's with libssl in python ( haven't got enough time to dig in properly )

**Comment by tianon** [comment]
Yeah, that's the bit I outlined back in https://github.com/docker-library/pypy/issues/24#issuecomment-409408657; good to know that's still the case. :disappointed:

**Comment by tianon** [comment]
I wonder if it would be possible for us to rebuild _just_ `_pypy_openssl.pypy3-60-x86_64-linux-gnu.so` without rebuilding _all_ of PyPy?

**Comment by tianon** [comment]
I've managed to get something that's working pretty successfully for 3.5 and 3.6 via running `/usr/local/lib_pypy/_ssl_build.py` post-install, but that doesn't work for 2.7 (it appears that on 2.7, `pypy` itself links directly to `libssl.so.1.0.0`, unlike on 3.x where it's a separate `.so` file under `lib_pypy` that does so and can thus be rebuilt externally).

**Comment by soerenmartius** [comment]
thanks for the heads-up, could you share some code?

**Comment by tianon** [comment]
```diff
diff --git a/Dockerfile-slim.template b/Dockerfile-slim.template
index 91a44c6..09c070c 100644
--- a/Dockerfile-slim.template
+++ b/Dockerfile-slim.template
@@ -1,4 +1,4 @@
-FROM debian:jessie-slim
+FROM debian:stretch-slim
 
 # ensure local pypy is preferred over distribution pypy
 ENV PATH /usr/local/bin:$PATH
@@ -31,7 +31,6 @@ RUN set -ex; \
 		bzip2 \
 		wget \
 	; \
-	rm -rf /var/lib/apt/lists/*; \
 	\
 	wget -O pypy.tar.bz2 "https://bitbucket.org/pypy/pypy/downloads/%%TAR%%-v${PYPY_VERSION}-${pypyArch}.tar.bz2"; \
 	echo "$sha256 *pypy.tar.bz2" | sha256sum -c; \
@@ -42,6 +41,12 @@ RUN set -ex; \
 # smoke test
 	%%CMD%% --version; \
 	\
+# rebuild ffi bits for compatibility with Debian Stretch+ (https://github.com/docker-library/pypy/issues/24#issuecomment-409408657)
+	apt-get install -y --no-install-recommends gcc libc6-dev libssl-dev; \
+	cd /usr/local/lib_pypy; \
+	%%CMD%% _ssl_build.py; \
+# TODO rebuild other cffi modules here too? (other _*_build.py files)
+	\
 	wget -O get-pip.py 'https://bootstrap.pypa.io/get-pip.py'; \
 	\
 	%%CMD%% get-pip.py \
@@ -58,6 +63,7 @@ RUN set -ex; \
 	[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark > /dev/null; \
 	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
 # smoke test again, to be sure
+	rm -rf /var/lib/apt/lists/*; \
 	%%CMD%% --version; \
 	pip --version
 
diff --git a/Dockerfile.template b/Dockerfile.template
index 14ef48e..5e42067 100644
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -1,4 +1,4 @@
-FROM buildpack-deps:jessie
+FROM buildpack-deps:stretch
 
 # ensure local pypy is preferred over distribution pypy
 ENV PATH /usr/local/bin:$PATH
@@ -23,14 +23,19 @@ RUN set -ex; \
 # this "case" statement is generated via "update.sh"
 	%%ARCH-CASE%%; \
 	\
-	wget -O pypy.tar.bz2 "https://bitbucket.org/pypy/pypy/downloads/%%TAR%%-v${PYPY_VERSION}-${pypyArch}.tar.bz2"; \
+	wget -O pypy.tar.bz2 "https://bitbucket.org/pypy/pypy/downloads/%%TAR%%-v${PYPY_VERSION}-${pypyArch}.tar.bz2" --progress=dot:giga; \
 	echo "$sha256 *pypy.tar.bz2" | sha256sum -c; \
 	tar -xjC /usr/local --strip-components=1 -f pypy.tar.bz2; \
 	find /usr/local/lib-python -depth -type d -a \( -name test -o -name tests \) -exec rm -rf '{}' +; \
 	rm pypy.tar.bz2; \
 	\
 # smoke test
-	%%CMD%% --version
+	%%CMD%% --version; \
+	\
+# rebuild ffi bits for compatibility with Debian Stretch+ (https://github.com/docker-library/pypy/issues/24#issuecomment-409408657)
+	cd /usr/local/lib_pypy; \
+	%%CMD%% _ssl_build.py
+# TODO rebuild other cffi modules here too? (other _*_build.py files)
 
 RUN set -ex; \
 	\
```
