### ISSUE TITLE
preinstall pip and setuptools

### ISSUE THREAD

**Issue by KOLANICH** [docker-library/pypy#26]
https://gitlab.com/KOLANICH1/Chassis.py/-/jobs/83348020

**Comment by wglambert** [comment]
Those are both included in the image
https://github.com/docker-library/pypy/blob/4a71a30c057b858ae569f8465dffa8ce559ff225/3/Dockerfile#L45-L50

```console
$ docker run --rm -dit --name pypy pypy
$ docker exec -it pypy bash
root@9860b9354448:/# which pip3 && which pip
/usr/local/bin/pip3
/usr/local/bin/pip
root@9860b9354448:/# which easy_install
/usr/local/bin/easy_install
root@9860b9354448:/#
```

**Comment by KOLANICH** [comment]
I know. And that's strange that sometimes it doesn't work.
