### ISSUE TITLE
[pypy3] libpypy3-c.so Not found

### ISSUE THREAD

**Issue by cromefire** [docker-library/pypy#28]
## Steps to reproduce:
```
docker run pypy:3 pypy3 -c "print(\"okay\")"
```
## Results in:
```
pypy3: error while loading shared libraries: libpypy3-c.so: cannot open shared object file: No such file or directory
```

**Comment by cromefire** [comment]
You can some how get it work using:
```
docker run pypy:3 bash -c "pypy3 -c print\(\\\"okay\\\"\)"
```

**Comment by cromefire** [comment]
And in the docker file it also works using the json syntax (which uses no shell)

**Comment by wglambert** [comment]
You'd want this https://packages.debian.org/sid/pypy-lib

```dockerfile
FROM pypy

RUN apt-get update && apt-get install -y --no-install-recommends \
                pypy-lib \
        && rm -rf /var/lib/apt/lists/*
```

```console
$ docker run --rm pypy:test pypy3 -c "print(\"okay\")"
okay
```

**Comment by cromefire** [comment]
No the thing is there **is** a `libpypy3-c.so`  under `/usr/local/bin/` but it is only works if you use a shell script:
```
#!/bin/bash
pypy3 -c "print(\"okay\")"
```
but when calling it directly it fails.

https://packages.debian.org/jessie/pypy-lib is **`pypy2`** not `pypy3` and the basic gist of this container is to **not install pypy2 but pypy3** right?

Also `pypy-lib` **does not install libpypy3-c.so**: https://packages.debian.org/jessie/all/pypy-lib/filelist, nor any other python3 stuff. There has to be some other difference.

**Comment by cromefire** [comment]
According to the [pypy docs](https://pypy.org/download.html) **you should be able to download it and just run it**, the only question is, who's fault is this? Docker, this container or pypy? On my computer that totally works, just download and run the executable (so I bet it's not pypy).

**Comment by wglambert** [comment]
I went and tested your issue without modifications and can't seem to reproduce it.

```console
$ docker pull pypy:3
3: Pulling from library/pypy
Digest: sha256:81af2ca34d781b5efffe926e9d4c494496b51da8075e75ddce57cbdf1fbb3b7d
Status: Image is up to date for pypy:3

$ docker run pypy:3 pypy3 -c "print(\"okay\")"
okay
```

libpypy3 is present in the image
```console
$ docker run --rm -dit --name pypy2 pypy:3
$ docker exec -it pypy2 bash
root@8ae0a0f06455:/# find / | grep libpypy
/usr/local/bin/libpypy3-c.so
/usr/local/bin/libpypy3-c.so.debug
```

Slim also works as expected
```console
$ docker run pypy:3-slim pypy3 -c "print(\"okay\")"
Unable to find image 'pypy:3-slim' locally
3-slim: Pulling from library/pypy
57936531d1ee: Already exists 
17bf8a581274: Pull complete 
72b48bc04e6b: Pull complete 
Digest: sha256:5a14883c363b4365cad9ebd74885dee5ae91961737c903c13d98502c75d7883a
Status: Downloaded newer image for pypy:3-slim
okay
```

**Comment by cromefire** [comment]
https://asciinema.org/a/8dlyk1Q4085YlgkyiZmFXQIVe

**Comment by cromefire** [comment]
But how can that be when docker images are the same on every machine?

My version is: `17.06.2-ce, build a04f55b`

**Comment by tianon** [comment]
Seems like you might have a corrupted image -- have you tried removing
all traces of the image layers and re-pulling it?

It could also be something like AppArmor or SELinux interfering, but
that seems less likely in this case.

**Comment by cromefire** [comment]
> Seems like you might have a corrupted image -- have you tried removing all traces of the image layers and re-pulling it?

Did not work, but the fact that is works on my server tells me that it seems to be some thing with docker, Thanks!
