### ISSUE TITLE
[pypy3] build fails because dublicate pip

### ISSUE THREAD

**Issue by cromefire** [docker-library/pypy#29]
```
pypy get-pip.py --disable-pip-version-check --no-cache-dir pip==18.1
Double requirement given: pip (already in pip==18.1, name='pip')
```
The solution is to simply remove the section where pip gets installed

**Comment by tianon** [comment]
If we remove that section we won't get `pip` at all.

This is actually https://github.com/pypa/get-pip/issues/37 (see also https://github.com/pypa/get-pip/issues/38).

Once those are resolved, this will fix itself.

(The `python` image is currently suffering from the same problem.)

**Comment by cromefire** [comment]
why don't you use `pypy3 -m ensurepip`?

**Comment by tianon** [comment]
That doesn't allow us to specify an explicit `pip` version, and the last time I tested it, reinstalling `pip` over the top left files behind.

This `get-pip` issue should be temporary, and doesn't affect any built images.

If the problem persists too long, we'll implement a workaround.
