### ISSUE TITLE
Update to pypy 7.0 (Python 3.6), which TAG to use to pull it?

### ISSUE THREAD

**Issue by giodegas** [docker-library/pypy#31]
Since the twitter announcement, I am trying to pull the new pypy 7.0 image.
But if I do:

    docker pull pypy:latest

the running the container, I always get:

    Python 3.5.3 (fdd60ed87e94, Apr 24 2018, 06:10:04)
    [PyPy 6.0.0 with GCC 6.2.0 20160901] on linux

even if the image results updated less than 2 hours ago.
Why?

**Comment by wglambert** [comment]
It's in the process of being pushed to Dockerhub https://github.com/docker-library/official-images/pull/5439

https://github.com/docker-library/pypy#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by giodegas** [comment]
very good, now it works.
But when I start my container:

    docker run -it --name pypy pypy:latest /bin/bash
    root@5e5dd187b141:/# pypy3
    Python 3.5.3 (928a4f70d3de, Feb 08 2019, 10:42:58)
    [PyPy 7.0.0 with GCC 6.2.0 20160901] on linux
    Type "help", "copyright", "credits" or "license" for more information.  
    >>>> f'{2}'
    '2'
 
it seems to support the Python 3.6 syntax, but continue to print the 3.5.3 banner.
Can it it fixed, or there is a reason about it?
Thank's.

**Comment by tianon** [comment]
`:latest` is not based on Python 3.6 -- support for 3.6 is experimental in PyPy.  You want `:3.6` instead if you want to test the new 3.6 support.
