### ISSUE TITLE
Alpine images

### ISSUE THREAD

**Issue by oberstet** [docker-library/pypy#5]
It would be nice to have image versions based on Alpine Linux, similar to what CPython provides ...

**Comment by SoaringTiger** [comment]
+1

**Comment by JayH5** [comment]
The official PyPy builds are not compatible with Alpine Linux. Building PyPy for Alpine Linux from source is a non-trivial task. While you can build CPython from source in a Travis build in ~4 minutes, PyPy takes around 30-60 minutes on a dedicated host. PyPy also needs patching to build on Alpine.

I've managed to get PyPy2 building for Alpine Linux: https://github.com/JayH5/alpine-pypy. Also made some Docker images: https://github.com/JayH5/docker-alpine-pypy. This is half shameless plug/half this may be useful if anybody wants to build PyPy for their Alpine containers.

**Comment by arthurdarcet** [comment]
@JayH5 Could you open a pull request adding your Dockerfiles here under alpine tags?

**Comment by oberstet** [comment]
for comparison, here are resulting image sizes (uncompressed):

```
oberstet@thinkpad-t430s:~/scm/3rdparty/docker-alpine-pypy/2/slim$ docker images pypy:2-slim
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
pypy                2-slim              04c79a03c8b4        11 days ago         197MB
oberstet@thinkpad-t430s:~/scm/3rdparty/docker-alpine-pypy/2/slim$ docker images pypy2-alpine-slim
REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE
pypy2-alpine-slim   latest              ae2696d8a9ec        About a minute ago   132MB
```

**Comment by oberstet** [comment]
IMO, ideally, we had Alpine images of PyPy 2 and 3 for all archs x86-64, armhf, aarch64, x86-32, ... because, whatever sw is able to run on top of PyPy could profit from publishing a Docker image for production that includes the sw, and which is based on the Alpine flavor to minimize resource consumption at scale deployments.

**Comment by pjenvey** [comment]
The tkinter patch has been upstreamed to pypy: https://bitbucket.org/pypy/pypy/issues/2509/support-alpine-linux

So pypy2-v5.9.0 (to be released shortly) should likely work on Alpine now.

@JayH5 and anyone else, please upstream anything else needed to the PyPy bitbucket!

**Comment by JayH5** [comment]
@pjenvey thanks for the update. That means PyPy2 should build on Alpine now without patches 🎉 

I also saw [this commit](https://bitbucket.org/pypy/pypy/commits/3d878f5a314f415c867c04debd4c8c079ce4e3ed) a while ago that should remove the need for one of the PyPy3 patches.

That being said, unfortunately I personally haven't had and probably won't have the time in the near future to upstream my patches to PyPy. I will try keep my repo up-to-date when a new PyPy release arrives, but I might be a bit slow about that.

**Comment by jmagnusson** [comment]
Any updates here? Are patches still needed for pypy under alpine, @JayH5?

**Comment by JayH5** [comment]
@jmagnusson I haven't tried PyPy 5.10.x yet, but I think PyPy3 will still require patches. PyPy on Alpine Linux also suffers from docker-library/python#211, and I haven't found a way to apply something like docker-library/python#248 to fix it. Sorry, PyPy on Alpine Linux just hasn't been a priority for me recently so I haven't worked on it much.

**Comment by tianon** [comment]
Unfortunately, until this is something that's officially supported by the PyPy project, it isn't something we reasonably can support (especially given the non-trivial nature of building PyPy from source).  I think "it builds successfully" is probably not quite enough here. :see_no_evil:

I was hoping I could point to Alpine's own packages for folks who need this, but it appears even they only include PyPy in Alpine Edge: :grimacing:

https://pkgs.alpinelinux.org/packages?name=pypy*&branch=edge&arch=x86_64 vs https://pkgs.alpinelinux.org/packages?name=pypy*&branch=v3.15&arch=x86_64

Given this, I'm inclined to close this for now, and revisit once/if we get official released binaries that work on Alpine? :see_no_evil:

**Comment by oberstet** [comment]
fwiw, personally, I am not using Alpine anymore, but mostly just a stock/plain Ubuntu for Docker these days, or snaps for embedded, so yeah, given the limits on resources we all have to live with, screw it for now sounds good for me=)

**Comment by cirospaciari** [comment]
Some update on alpine images/official release?

**Comment by tianon** [comment]
Pursuant to https://github.com/docker-library/pypy/issues/5#issuecomment-1042461711, I'm going to close this for now:

> [We will] revisit once/if we get official released binaries that work on Alpine
