### ISSUE TITLE
pypy3-libs missing

### ISSUE THREAD

**Issue by Hendiadyoin1** [docker-library/pypy#50]
When trying to use uwsgi to start a django-project I get the Error:
> unable to load pypy library: libpypy-c.so: cannot open shared object file: No such file or directory

after a short goolge search i find it is related to the pypy-libs package, or in the py3 case propably the pypy3-libs package, which is not preinstalled with the container and the path for it is not deposited for later installation.

**Comment by wglambert** [comment]
Seems similar to https://github.com/docker-library/pypy/issues/28

Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by tianon** [comment]
See also https://github.com/docker-library/pypy/issues/46, especially https://github.com/docker-library/pypy/issues/46#issuecomment-735959220 -- you need to specify both `--pypy-home` and `--pypy-lib` (`--pypy-home /opt/pypy --pypy-lib /opt/pypy/bin/libpypy3-c.so`).
