### ISSUE TITLE
Remove python 2.7 installation inside pypy images

### ISSUE THREAD

**Issue by ShadowJonathan** [docker-library/pypy#52]
In (at least) `pypy:3.7`, `/usr/bin/python` refers to python 2.7.

Aside from the fact 2.7 is deprecated and EOL, can `/usr/bin/python` inside this image please refer to `pypy` instead? (so that any `python` commands will automatically use `pypy`)

**Comment by wglambert** [comment]
Its an unfortunate side-effect of using the buildpack-deps image in the non-slim variants https://github.com/docker-library/docs/tree/master/python#multiple-python-versions-in-the-image
`pypy:slim` doesn't have python in it
