### ISSUE TITLE
Pypy ppc64le images missing from hub.docker.com

### ISSUE THREAD

**Issue by jennydaman** [docker-library/pypy#60]

**Comment by tianon** [comment]
As seen on https://www.pypy.org/download_advanced.html, it's unfortunately only supported upstream for PyPy 2.7, but given https://foss.heptapod.net/pypy/pypy/-/issues/2646 it's unfortunately not something we can correctly support in our builds.

https://github.com/docker-library/pypy/blob/c82a64347c9b1cb02b3d695a5ddee66b8c219d1d/versions.sh#L146-L148

**Comment by jennydaman** [comment]
I see, thanks!

The DockerHub repo was tagged with "PowerPC LE", but since Python 2 is deprecated, maybe the tag should be removed?

**Comment by tianon** [comment]
Unfortunately we don't have any control over the labels that get displayed there.  I would suggest referring to the "Supported architectures" further down in the image description instead (which is something we _can_ control, and is updated with what the supported versions include, not just any old tagged image).

I also went to double check that our reasons for excluding were still valid and correct, and the latest release of PyPy is 7.3.5 but the latest release with ppc64le support is 7.3.1, so even if it worked it wouldn't get included. :disappointed:
