### ISSUE TITLE
Use a newer version of setuptools for pypy3

### ISSUE THREAD

**Issue by olliemath** [docker-library/pypy#62]
https://github.com/docker-library/pypy/pull/61 managed to break our images in subtle ways with issues at runtime (rather than install) - I'm unsure how to upstream this as the exact issue is hard to pin down (see below image).

The fix was to revert back to the python3.7 version of setuptools. This should be the default, rather than supporting pypy 2.7 by using setuptools 44.x in the 3.7 image.

![image](https://user-images.githubusercontent.com/10986467/133152390-83c65091-0609-4771-a971-245a2dc0aec0.png)

**Comment by tianon** [comment]
I was afraid of this. :disappointed:

I suppose we should mirror https://github.com/docker-library/python/pull/647 and look at https://foss.heptapod.net/pypy/pypy/-/blob/release-pypy2.7-v7.3.5/lib-python/2.7/ensurepip/__init__.py vs https://foss.heptapod.net/pypy/pypy/-/blob/release-pypy3.7-v7.3.5/lib-python/3/ensurepip/__init__.py

Concretely, that would mean:

- 2.7: pip 20.0.x + setuptools 44.0.x
- 3.7: pip 20.1.x + setuptools 47.1.x

**Comment by tianon** [comment]
I've got a proposal up in #63 that avoids us scraping/choosing versions at all (and instead trusting `pypy` to choose the appropriate versions).

**Comment by olliemath** [comment]
Thanks, that seems sensible
