### ISSUE TITLE
pypy is built against an ancient version of SQLite

### ISSUE THREAD

**Issue by remram44** [docker-library/pypy#68]
It seems that recent builds of the `pypy` docker image have used SQLite 3.7.17 from 2013. SQLite 3.8 was released in August 2013.

I don't think this is deliberate, since the `pypy` image used to have a more recent SQLite library and this recently changed.

In my case, I am running this code:

```python
db = sqlite3.connect('')
db.execute('''PRAGMA application_id=0x54677474;''')
```
and today this started raising `_sqlite3.OperationalError: unrecognized token: "0x54677474"`. Support for hexadecimal integers was added to SQLite version 3.8.6 (2014-08-15), so pypy is really the only place where this doesn't work.

**Comment by tianon** [comment]
Oh, very interesting -- I've just opened https://github.com/docker-library/pypy/pull/70, which I _hope_ will be an appropriate fix for this. :crossed_fingers:
