### ISSUE TITLE
Update to pypy 5.3 ?

### ISSUE THREAD

**Issue by jaredkipe** [docker-library/pypy#7]
pypy 5.3 has been out for a little while now, would be nice to get a version bump here as well

Thank you!

**Comment by tianon** [comment]
Ah, they changed the filename format on us!  Thanks for the heads up! :+1:

**Comment by jaredkipe** [comment]
I noticed the download file name change as well, but I assumed I didn't understand the mysteries behind the names...

Thanks again.
