### ISSUE TITLE
Move "docker pull pypy:3" to pypy3.8 instead of pypy3.7

### ISSUE THREAD

**Issue by mattip** [docker-library/pypy#75]
The PyPy team is no longer releasing PyPy3.7 and would prefer people use PyPy3.8 by default. Is there a way to reconfigure the `pypy:3` tag to point to PyPy3.8? See also https://foss.heptapod.net/pypy/pypy/-/issues/3606#note_184761

**Comment by mattip** [comment]
Strange, PR #66 should have solved this issue. Any ideas what is going on?

**Comment by wglambert** [comment]
Pypy's latest release is 7.3.9 https://doc.pypy.org/en/latest/release-v7.3.9.html and the latest Python 3.8 is 3.8.13

![image](https://user-images.githubusercontent.com/26428991/168862065-6de39804-3cf3-443b-9e6c-efe86578bbb1.png)


```console
$ docker run -it --rm pypy:3 bash
Unable to find image 'pypy:3' locally
3: Pulling from library/pypy
67e8aa6c8bbc: Pull complete
627e6c1e1055: Pull complete
0670968926f6: Pull complete
5a8b0e20be4b: Pull complete
b0b10a3a2784: Pull complete
b4ed3a98b6c7: Pull complete
117081c66124: Pull complete
441adc8f7971: Pull complete
Digest: sha256:6a56190558e25c07b497c43fc0340ee5235b7887b164875db77af5d01b7cc334
Status: Downloaded newer image for pypy:3

root@7e40f5ce0f77:/# pypy -V
Python 3.8.13 (4b1398fe9d76ad762155d03684c2a153d230b2ef, Mar 29 2022, 07:08:24)
[PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]

root@7e40f5ce0f77:/# ls /opt/pypy/lib/ | grep pypy
pypy3.8
```

So it is pulling this `pypy:3.8` Dockerfile https://github.com/docker-library/pypy/blob/master/3.8/bullseye/Dockerfile

The build's smoke test to verify it's `pypy 3.8` https://github.com/docker-library/pypy/runs/5264194395?check_suite_focus=true#step:5:269

**Comment by rouilj** [comment]
I was the one who started this in the PyPY tracker. Maybe this is a misunderstanding
in what the version string means.

I read: pypy -V
Python 3.8.13 (4b1398fe9d76ad762155d03684c2a153d230b2ef, Mar 29 2022, 07:08:24)
[PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]

to mean: PyPY version 7.3.9 implementing python version 3.8.13.

From https://downloads.python.org/pypy/ it looks like PyPY version 7.3.9 with python version 3.9 is the most current, but there is also a recent (march 29th) version of the 3.8 release which looks like what is in the docker.

So I think this is a misunderstanding and can be closed.
