### ISSUE TITLE
3.10 image

### ISSUE THREAD

**Issue by olliemath** [docker-library/pypy#78]
Hello, I see that you've updated to the new 7.3.12 release of pypy. That release [also contains a python 3.10 interpreter](https://doc.pypy.org/en/latest/release-v7.3.12.html) Would it be possible to add this to the official images (there will be no more releases of 3.8) ?

Happy to open a PR if that helps.

**Comment by tianon** [comment]
Oh nice, thanks for noticing and raising! https://github.com/docker-library/pypy/pull/79 :+1:
