### ISSUE TITLE
2-5.3.1 tag appears to be missing or broken

### ISSUE THREAD

**Issue by JayH5** [docker-library/pypy#9]
```
> $ docker pull pypy:2-5.3.1
Pulling repository docker.io/library/pypy
Tag 2-5.3.1 not found in repository docker.io/library/pypy
```

<img width="722" alt="screen shot 2016-07-04 at 3 22 10 pm" src="https://cloud.githubusercontent.com/assets/1748643/16561742/236d2b42-41fb-11e6-87dc-80d3fe4f5feb.png">

**Comment by yosifkit** [comment]
Must've been a hiccup on the docker hub. We poked it by pushing the image from the build server.  It should be available shortly.

**Comment by JayH5** [comment]
Fixed. Thank you!
